name: Create universal2 python release

on: [workflow_call]

jobs:
  build:
    name: Create Release
    runs-on: macos-latest
    steps:
        - uses: actions/checkout@v2
        - name: Install latest Rust nightly
          uses: actions-rs/toolchain@v1
          with:
            toolchain: nightly-2021-09-14
            override: true
            components: rustfmt, clippy
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: ${{ matrix.python-version }}
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install maturin==0.11.0
        - name: switch to pip test
          run: |
            pyton -m pip install --index-url https://test.pypi.org/simple/
        - name: Publish wheel
          shell: bash
          env:
            MATURIN_PASSWORD: ${{ secrets.PYPI_PASS }}
          run: |
            rm py-polars/README.md
            cp README.md py-polars/README.md
            cd py-polars
            rustup override set nightly-2021-09-14
            export RUSTFLAGS='-C target-feature=+fxsr,+sse,+sse2,+sse3'
            maturin publish \
            --universal2 \
            --skip-existing \
            -o wheels \
            -i python \
            --username theophaniel \
